# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://matteo.gaito/wedding/
title: Matrimonio Marta e Matteo
email: mem@gaito.net
author: Matteo Gaito
description: > # "Homepage del matrimonio di Marta e Matteo. "
copyright: 'Copyright &copy; 2019 Marta e Matteo. All Rights Reserved.'
credits: 'Credits: Wikipedia and Chugky'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

